# Do not modify this file!  It was generated by ‘nixos-generate-config’.
# Please make changes to configuration.nix or one of the modules it references
# instead.
#
# Despite being a generated file, this is still checked in to our repository.
# This makes it possible to evaluate the top-level ``configuration.nix`` on
# developer systems which is sometimes useful.  If the deployment hardware
# changes it might be necessary to generate a new version of this file on the
# system and then check it in.  Since the deployment hardware is really a VM
# this isn't too likely to happen (more likely is that we'll provision a new
# VM and need a new hardware configuration for it - unless it happens to be
# configured just like this one, which it might be).

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "virtio_pci" "virtio_scsi" "xhci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/32c12782-e288-4ae2-a2bd-796b37087ff4";
      fsType = "ext4";
    };

  swapDevices = [ ];

}
